Feature: Tags Concept

  @Sanity @End2End
  Scenario: Verify Login
    Given This is valid Login Test

  @Sanity @End2End
  Scenario: Verify Logout
    Given This is logout Test

  @Regression @End2End
  Scenario: Verify Search
    Given This is Search Test

  @Regression @End2End
  Scenario: Verify Advanced Search
    Given This is Advanced Search

  @End2End
  Scenario: Verify Prepaid Recharge
    Given This is Prepaid Recharge

  @End2End
  Scenario: Verify Postpaid Recharge
    Given This is Postpaid Recharge

